blogs/urls.py
from django.urls import path,re_path
from .import views

app_name='blogs'

urlpatterns = [
    path('', views.blog_post, name='blog_home'),

    path('create/', views.post_create, name="create"),

    path('<str:slug>', views.post_detail, name='detail'),

    # path('tag/<slug:tag_slug>/', views.blog_post, name='tagged'),
    path('tag/<slug:tag_slug>/', views.blog_post, name='tagged'),
    # re_path(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    path('search/search-post', views.search_post, name='search')
]

communityBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views
from contacts import views as contacts_view
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('', views.homepage, name='activity'),
    path('', views.homepage, name='team'),
    # path('', views.homepage, name='contact'),
    path('blog/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contacts.urls')),
    path('activity/', include('todos.urls')),
    # path('team', teams_view.view_team, name='team')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True, upload_to='media/')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    tags = TaggableManager(verbose_name='Category')

    # objects = PostManager()

    def __str__(self):
        return self.title

    def short_body(self):
        return self.body[:50] + "..."

blogs/forms.py
from django import forms
from.import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'thumb', 'tags']

blogs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from django.views.generic import ListView

from . import forms
from blogs.models import Post
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
# Create your views here.

"""Here is a blog post function that takes request"""


def blog_post(request, tag_slug=None):
    results = Post.objects.all()
    # tag_slug = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        relates = results.filter(tags__in=[tag])
        return render(request, 'blog/related.html', {'relates': relates, 'tag': tag, 'results': results})
    if len(results) == 0:
        empty_msg = "No post to show"
        return render(request, 'blog/blog_post.html', {'empty': empty_msg})
    else:
        return render(request, 'blog/blog_post.html', {'results': results})


def post_detail(request, slug):
    detail = Post.objects.get(slug=slug)
    return render(request, 'blog/post_detail.html', {'detail': detail})


def search_post(request):
    if request.method == "POST":
        searched = request.POST.get('searched-value')
        matches = Post.objects.filter(title__contains=searched)
        return render(request, 'blog/search.html', {'values': searched, 'matches': matches})
    else:
        return render(request, 'blog/search.html')


@login_required(login_url="/accounts/login/")
def post_create(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)  # Pre-saving
            instance.author = request.user  # adding user as Author to the instance of post
            instance.save()  # saving post with author
            form.save_m2m()  # saving tag with this method found on form not on instance
            return redirect('blogs:blog_home')
    else:
        form = forms.CreatePost()
    return render(request, 'blog/post_create.html', {'myform': form})

blogs/templates/blog/blog_post.html
{% extends 'base.html' %}

{% block content %}

{% if empty %}
<h1>{{empty}}</h1>

{% else %}

<div class="search">
    <form action="{% url 'blogs:search' %}" method="POST" class="search-form">
        {% csrf_token %}
        <input type="text" placeholder="Search ..." name="searched-value" required>
        <input type="submit" value="Search">
    </form>
</div>

    <h1>Post Lists</h1>
    <div class="posts">
<!--        {% if tag %}-->
<!--&lt;!&ndash;        <p>You tagged by <em>"{{tag.name}}"</em></p>&ndash;&gt;-->
<!--        {% endif %}-->
        {% for result in results %}
        <div class="post">
              <a href="{% url 'blogs:detail' slug=result.slug %}"><h2>{{result.title}}</h2>
                  <p>{{result.short_body}}</p>
                  <p>{{result.date}}</p>
              </a>
              <p class="author"><span>Author: </span>{{result.author}}</p>
               <p>
                   {% for tag in result.tags.all %}
                    <p><a href="{% url 'blogs:tagged' tag.slug %}">{{tag.name}}</a></p>
                   {% endfor %}
        </div>
            {% endfor %}
    </div>
{% endif %}



{% endblock %}

blogs/templates/blog/post_create.html
{% extends 'base.html' %}

{% block content %}
<div class="post_create">
    <h2>Create a new Post</h2>
    <form action="{% url 'blogs:create' %}" class="site-form create-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{myform}}
        <input type="submit" value="Create">
    </form>
</div>
<script src="/static/js/slugify.js"></script>
{% endblock %}

blogs/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
        <div class="post-detail">
         <div class="post post-barred">
           <ul>
               <img src="{{detail.thumb.url}}" alt="" class="img">
               <h2>{{detail.title}}</h2>
               <p>{{detail.body}}</p>
               <p>{{detail.date}}</p>
           </ul>
         </div>
        </div>

{% endblock %}

blogs/templates/blog/related.html
{% extends 'base.html' %}

{% block content %}
<div class="related-post">
        <h2>Related Posts</h2>
        <div class="relate">
        {% for relate in relates %}
             <div><img src="{{relate.thumb.url}}" alt=""></div>
             <div><a href="">{{relate.title}}</a></div>
        {% empty %}
          <p>There is no similar posts</p>
        {% endfor %}
       </div>
</div>
{% endblock %}

blogs/templates/blog/search.html
{% extends 'base.html' %}

{% block content %}
<div class="search">
    <form action="{% url 'blogs:search' %}" method="POST" class="search-form">
        {% csrf_token %}
        <input type="text" placeholder="Search ..." name="searched-value" required>
        <input type="submit" value="Search">
    </form>
</div>
<!--<h1>You searched for {{values}}</h1>-->
<div class="matches">
        {% if matches %}
        {% for match in matches %}
          <div class="match">
            <h2>{{match.title}}</h2>
            <p>{{match.body}}</p>
          </div>
        {% endfor %}

        {% else %}
        <p>Your search '- <em>{{values}}</em> -' did not match any posts.</p>
        <a href="{% url 'blogs:blog_home' %}" class="back">Back to posts</a>
        {% endif %}
</div>
{% endblock %}