accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
   path('signup/', views.signup_view, name='signup'),
   path('login/', views.login_view, name='login'),
   path('logout/', views.logout_view, name='logout')
]

blogs/urls.py
from django.urls import path,re_path
from .import views

app_name='blogs'

urlpatterns = [
    path('', views.blog_post, name='blog_home'),

    path('create/', views.post_create, name="create"),

    path('<str:slug>', views.post_detail, name='detail'),

    # path('tag/<slug:tag_slug>/', views.blog_post, name='tagged'),
    path('tag/<slug:tag_slug>/', views.blog_post, name='tagged'),
    # re_path(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    path('search/search-post', views.search_post, name='search')
]

communityBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views
from contacts import views as contacts_view
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('', views.homepage, name='activity'),
    path('', views.homepage, name='team'),
    # path('', views.homepage, name='contact'),
    path('blog/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contacts.urls')),
    path('activity/', include('todos.urls')),
    # path('team', teams_view.view_team, name='team')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path

from . import views

app_name='contacts'

urlpatterns = [

    path('', views.contact, name='contact'),
]

todos/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

app_name = 'todos'

urlpatterns = [

    path('<str:title>/', views.activity, name='what_we_do'),
]

templates/apart_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Community-Home</title>
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% block apart %}

{% endblock %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Community-Posts</title>
    <link rel="stylesheet" href="{% static 'css/blogs.css' %}">
</head>
<body>
<div class="wrapper">
        <header>
            <div><a href="{% url 'home' %}"  class="wrapper__logo"><img src="{% static '/logo/logo.png' %}" alt=""></a>
             Community</div>
                <nav>
                    <ul>
                        {% if user.is_authenticated %}
                        <li>
                            <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'blogs:create' %}" class="highlight">New Post</a></li>
                        <li><p>{{user.username}}</p></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>

                        {% endif %}
                    </ul>
                </nav>
        </header>
</div>

{% block content %}
{% endblock %}

</body>
</html>

templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Community-Home</title>
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>


 <nav class="navbar">
        <div class="max-width">
          <div class="logo"><a href="#"><img src="{% static 'logo/logo.png' %}" alt=""></a></div>
            <ul class="menu">
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#service">What we do</a></li>
                <li><a href="#team">Team</a></li>
                <li><a href="#blog">Blog</a></li>
                <li><a href="#contact">Get in touch</a></li>
            </ul>
        </div>
    </nav>

    <nav class="navbar">
        <div class="max-width">
          <div class="logo"><a href="#"><img src="{% static '/logo/logo.png' %}" alt=""></a></div>
            <ul class="menu">
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#service">What we do</a></li>
                <li><a href="#team">Team</a></li>
                <li><a href="#blog">Blog</a></li>
                <li><a href="#contact">Get in touch</a></li>
            </ul>
        </div>
    </nav>

    <!-- home section start -->
    <section class="home" id="home">
        <div class="max-width">
            <div class="home-content">
                <div>
                    <div class="text-1">A Community of Movie lovers</div>
                    <div class="text-2">"Here, it is a platform for movie lovers where we meet and chill by posting our concerns about a certain movie."</div>
                    <a href="#about" class="more-about">More About us</a>
                    <a href="{% url 'blogs:blog_home' %}">Join the Community</a>
                 </div>
            </div>
        </div>
    </section>

    <!-- about me section -->
    <section class="about" id="about">
        <div class="max-width">
            <h2 class="title">About Us</h2>
            <div class="about-content">
                <div class="column right">
                    {% if aboutus %}
                    {% for about in aboutus %}
                    <div class="text">"{{about.heading}}"</div>
                    <p>{{about.description}}</p>
                </div>
                <div class="column left">
                    <img src="{% static 'logo/logo.png' %}" alt="">
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>

    <!-- service section start -->
    <section class="service" id="service">
        <div class="max-width">
            <h2 class="title">What we do</h2>
            <div class="service-content">
                <div class="card">
                        {% if todos %}
                        {% for todo in todos %}
                    <div class="box">
                        <i class="{{todo.icon}}"></i>
                        <div class="text">{{todo.title}}</div>
                        <p>{{todo.show_short_activity_desc}}</p>
                        <a href="{% url 'todos:what_we_do' title=todo.title %}">Read More</a>
                    </div>
                    {% endfor %}
                    {% endif %}
               </div>
            </div>
        </div>
    </section>

    <!-- team section start -->
    <section class="team" id="team">
        <div class="max-width">
            <h2 class="title">Our Team</h2>
            <div class="container">
                <div class="row">
                         {% if teams %}
                         {% for team in teams %}
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-4 offset-2">
                                    <img   class="rounded-pill" width="175" height="175" src="{{team.image.url}}" alt="">
                                </div>
                                <div class="col-md-6">
                                    <p class="name"><strong>Name:</strong><span> {{team.name}}</span></p>
                                     <p class="mate-title"><strong>Title:</strong><span class="desc"> {{team.title}}</span></p>
                                     <p class="desc"> {{team.description}}</p>
                                </div>
                            </div>

                        </div>
                    {% endfor %}
                    {% endif %}
                </div>

            </div>

        </div>
    </section>
<!-- blog section start -->
<section class="blog" id="blog">
        <div class="max-width">
            <h2 class="title">Blog Posts</h2>
            <div class="blog-content">

                <div class="card">
                    {% if blogs %}
                    {% for blog in blogs %}
                            <div class="box">
                                <a href="{% url 'blogs:detail' slug=blog.slug %}"><img src="{{blog.thumb.url}}" alt=""></a>
                                <p>{{blog.short_body}}</p>
                                <p>{{blog.slug}}</p>
                                <div class="text">{{blog.title}}</div>
                            </div>
                    {% endfor %}
                    {% else %}
                    <h2>No blogs</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

    <!-- contact section start -->
    <section class="contact" id="contact">
        <div class="max-width">
            <h2 class="title">Get in touch</h2>
            <div class="contact-content">
                <div class="column">
                    <div class="left">
                        <h2>Social links</h2><br>
                        <div class="left-top">
                            <a href="https://www.instagram.com/aimablenyakamwe/"><img src="{% static '/images/icon/instagram.svg' %}" alt=""></a>
                            <a href="https://twitter.com/N1Aimable"><img src="{% static '/images/icon/twitter.svg' %}" alt=""></a>
                        </div>
                        <div class="left-down">
                            <a href="#"><img src="{% static '/images/icon/facebook.svg' %}" alt=""></a>
                            <a href="" title="(+250 795439924)"><img src="{% static '/images/icon/whatsapp.svg' %}" alt=""></a>
                        </div>
                    </div>

                    <div class="middle">
                        <h2>Site map</h2>
                        <a href="#home">Home</a>
                        <a href="#team">Our team</a>
                        <a href="#blog">Blog post</a>
                    </div>

                    <div class="right">
                            <h2>Contact us</h2>
                            <form action="{% url 'contacts:contact' %}" method="POST">
                                {% csrf_token %}
                                <input type="email" placeholder="Enter Email address" name="email" required>
                                <input type="text" placeholder="Enter Subject" name="subject" required>
                                <textarea name="body" id="" cols="30" rows="10" required></textarea>
                                <input type="submit" value="Submit">
                            </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- footer section start -->
    <footer>
        <span>Created by N.A & Philly<span>| 2021 &copy; All Rights reserved.</span> </span>
    </footer>

</body>
</html>